sudo: required
services:
  - docker
before_install: 
  - docker build -t bhupesh0215/react-test -f ./client/Dockerfile.dev ./client
script: 
  - docker run bhupesh0215/react-test npm-test -- --coverage
after_success: 
  - docker build -t bhupesh0215/multi-client ./client
  - docker build -t bhupesh0215/multi-nginx ./nginx
  - docker build -t bhupesh0215/multi-server ./server
  - docker build -t bhupesh0215/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bhupesh0215/multi-clien
  - docker push bhupesh0215/multi-nginx
  - docker push bhupesh0215/multi-server
  - docker push bhupesh0215/multi-worker
